### ISSUE TITLE
Upgrade this to Create React App v2

### ISSUE THREAD

**Issue by alejandronanez** [react-medellin/flexbox-playground#38]
Useful links:
- https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#updating-to-new-releases
- https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md#migrating-from-1x-to-203
- https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

**Comment by angelitaooo** [comment]
I want to work on this, please!
