### ISSUE TITLE
flex property values don't match on fresh page

### ISSUE THREAD

**Issue by slacle** [react-medellin/flexbox-playground#46]
**Describe the bug**
When the page is first loaded, the flex property values don't match with the rendered values.

**To Reproduce**
Open the app and see that justify-content and align-content are set to center, while the boxes displayed will be set to flex-start.

**Expected behavior**
The boxes should reflect the selected values from the moment the page is first loaded.

**Screenshots**
![flex-values](https://user-images.githubusercontent.com/10146319/47630562-76449a80-db0f-11e8-9a26-c5dff57c2d9a.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: chrome
 - Version:  69

**Comment by alejandronanez** [comment]
Closed by https://github.com/react-medellin/flexbox-playground/pull/47
